"""
Synthora Pydantic Schemas

This module exports all Pydantic schemas for request/response validation.
"""

from app.schemas.common import (
    BaseSchema,
    TimestampSchema,
    IDSchema,
    PaginationParams,
    PaginatedResponse,
    ErrorDetail,
    ErrorResponse,
    SuccessResponse,
    HealthResponse,
    MessageResponse,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    RoleUpdate,
    StatusUpdate,
    UserResponse,
    UserProfileResponse,
    UserListResponse,
    UserStatsResponse,
    FirebaseTokenRequest,
    LoginResponse,
    SetupStatusResponse,
)
from app.schemas.subscription import (
    SubscriptionResponse,
    SubscriptionStatusResponse,
    PlanFeatures,
    PlanInfo,
    PlansResponse,
    CheckoutRequest,
    CheckoutResponse,
    PortalResponse,
    WebhookResponse,
)
from app.schemas.integration import (
    IntegrationResponse,
    IntegrationRevealResponse,
    AvailableIntegration,
    AvailableIntegrationsResponse,
    UserIntegrationsResponse,
    IntegrationCreate,
    IntegrationUpdate,
    IntegrationValidateResponse,
)
from app.schemas.template import (
    VideoStructureConfig,
    VisualStyleConfig,
    AudioConfig,
    ScriptPromptConfig,
    PlatformOptimizationConfig,
    TemplateConfigSchema,
    TemplateCreate,
    TemplateUpdate,
    TemplateResponse,
    TemplateListItem,
    TemplateListResponse,
    TemplateConfigResponse,
)
from app.schemas.video import (
    VideoGenerationRequest,
    SwapIntegrationRequest,
    StepStatus,
    VideoStatusResponse,
    VideoResponse,
    VideoListItem,
    VideoListResponse,
    VideoGenerationResponse,
)
from app.schemas.social_account import (
    SocialAccountResponse,
    SocialAccountListResponse,
    OAuthInitResponse,
    OAuthCallbackResponse,
    DisconnectRequest,
)
from app.schemas.post import (
    PostCreate,
    PostUpdate,
    PostResponse,
    PostListResponse,
    CalendarDayItem,
    CalendarResponse,
    PostCreateResponse,
    PublishNowRequest,
)
from app.schemas.analytics import (
    AnalyticsMetrics,
    AnalyticsResponse,
    OverviewResponse,
    PlatformMetrics,
    PlatformComparisonResponse,
    PostAnalyticsResponse,
    TimeSeriesDataPoint,
    TimeSeriesResponse,
    TopPerformingItem,
    TopPerformingResponse,
    HeatmapResponse,
    SyncResponse,
    AnalyticsSyncRequest,
)
from app.schemas.suggestion import (
    SuggestionResponse,
    SuggestionListItem,
    SuggestionListResponse,
    UnreadCountResponse,
    PostingTimeAnalysis,
    PostingTimeResponse,
    ContentIdea,
    ContentIdeasResponse,
    TrendItem,
    TrendsResponse,
    PerformancePrediction,
    PerformancePredictionResponse,
    ImprovementItem,
    ImprovementsResponse,
    GenerateSuggestionsResponse,
    MarkReadRequest,
    DismissRequest,
    GenerateSuggestionsRequest,
)
from app.schemas.notification import (
    NotificationResponse,
    NotificationListItem,
    NotificationListResponse,
    UnreadCountResponse as NotificationUnreadCountResponse,
    MarkReadResponse,
    DismissResponse,
    MarkReadRequest as NotificationMarkReadRequest,
    DismissRequest as NotificationDismissRequest,
    BroadcastRequest,
    BroadcastResponse,
)
from app.schemas.admin import (
    AdminUserItem,
    AdminUserListResponse,
    AdminUserStats,
    AdminUserDetailResponse,
    UpdateUserRoleRequest,
    UpdateUserStatusRequest,
    UserStats,
    VideoStats,
    PostStats,
    SubscriptionStats,
    PlatformStatsResponse,
    DailyDataPoint,
    ActivityStatsResponse,
    TopUserItem,
    TopUsersResponse,
    SettingItem,
    SettingsResponse,
    SetSettingRequest,
    FeatureFlags,
    SystemLimits,
    TemplateUsageItem,
    TemplateStatsResponse,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampSchema",
    "IDSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",
    "MessageResponse",
    
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "RoleUpdate",
    "StatusUpdate",
    "UserResponse",
    "UserProfileResponse",
    "UserListResponse",
    "UserStatsResponse",
    "FirebaseTokenRequest",
    "LoginResponse",
    "SetupStatusResponse",
    
    # Subscription
    "SubscriptionResponse",
    "SubscriptionStatusResponse",
    "PlanFeatures",
    "PlanInfo",
    "PlansResponse",
    "CheckoutRequest",
    "CheckoutResponse",
    "PortalResponse",
    "WebhookResponse",
    
    # Integration
    "IntegrationResponse",
    "IntegrationRevealResponse",
    "AvailableIntegration",
    "AvailableIntegrationsResponse",
    "UserIntegrationsResponse",
    "IntegrationCreate",
    "IntegrationUpdate",
    "IntegrationValidateResponse",
    
    # Template
    "VideoStructureConfig",
    "VisualStyleConfig",
    "AudioConfig",
    "ScriptPromptConfig",
    "PlatformOptimizationConfig",
    "TemplateConfigSchema",
    "TemplateCreate",
    "TemplateUpdate",
    "TemplateResponse",
    "TemplateListItem",
    "TemplateListResponse",
    "TemplateConfigResponse",
    
    # Video
    "VideoGenerationRequest",
    "SwapIntegrationRequest",
    "StepStatus",
    "VideoStatusResponse",
    "VideoResponse",
    "VideoListItem",
    "VideoListResponse",
    "VideoGenerationResponse",
    
    # Social Account
    "SocialAccountResponse",
    "SocialAccountListResponse",
    "OAuthInitResponse",
    "OAuthCallbackResponse",
    "DisconnectRequest",
    
    # Post
    "PostCreate",
    "PostUpdate",
    "PostResponse",
    "PostListResponse",
    "CalendarDayItem",
    "CalendarResponse",
    "PostCreateResponse",
    "PublishNowRequest",
    
    # Analytics
    "AnalyticsMetrics",
    "AnalyticsResponse",
    "OverviewResponse",
    "PlatformMetrics",
    "PlatformComparisonResponse",
    "PostAnalyticsResponse",
    "TimeSeriesDataPoint",
    "TimeSeriesResponse",
    "TopPerformingItem",
    "TopPerformingResponse",
    "HeatmapResponse",
    "SyncResponse",
    "AnalyticsSyncRequest",
    
    # Suggestion
    "SuggestionResponse",
    "SuggestionListItem",
    "SuggestionListResponse",
    "UnreadCountResponse",
    "PostingTimeAnalysis",
    "PostingTimeResponse",
    "ContentIdea",
    "ContentIdeasResponse",
    "TrendItem",
    "TrendsResponse",
    "PerformancePrediction",
    "PerformancePredictionResponse",
    "ImprovementItem",
    "ImprovementsResponse",
    "GenerateSuggestionsResponse",
    "MarkReadRequest",
    "DismissRequest",
    "GenerateSuggestionsRequest",
    
    # Notification
    "NotificationResponse",
    "NotificationListItem",
    "NotificationListResponse",
    "NotificationUnreadCountResponse",
    "MarkReadResponse",
    "DismissResponse",
    "NotificationMarkReadRequest",
    "NotificationDismissRequest",
    "BroadcastRequest",
    "BroadcastResponse",
    
    # Admin
    "AdminUserItem",
    "AdminUserListResponse",
    "AdminUserStats",
    "AdminUserDetailResponse",
    "UpdateUserRoleRequest",
    "UpdateUserStatusRequest",
    "UserStats",
    "VideoStats",
    "PostStats",
    "SubscriptionStats",
    "PlatformStatsResponse",
    "DailyDataPoint",
    "ActivityStatsResponse",
    "TopUserItem",
    "TopUsersResponse",
    "SettingItem",
    "SettingsResponse",
    "SetSettingRequest",
    "FeatureFlags",
    "SystemLimits",
    "TemplateUsageItem",
    "TemplateStatsResponse",
]
