"""
Synthora Pydantic Schemas

This module exports all Pydantic schemas for request/response validation.
"""

from app.schemas.common import (
    BaseSchema,
    TimestampSchema,
    IDSchema,
    PaginationParams,
    PaginatedResponse,
    ErrorDetail,
    ErrorResponse,
    SuccessResponse,
    HealthResponse,
    MessageResponse,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    RoleUpdate,
    StatusUpdate,
    UserResponse,
    UserProfileResponse,
    UserListResponse,
    UserStatsResponse,
    FirebaseTokenRequest,
    LoginResponse,
    SetupStatusResponse,
)
from app.schemas.subscription import (
    SubscriptionResponse,
    SubscriptionStatusResponse,
    PlanFeatures,
    PlanInfo,
    PlansResponse,
    CheckoutRequest,
    CheckoutResponse,
    PortalResponse,
    WebhookResponse,
)
from app.schemas.integration import (
    IntegrationResponse,
    IntegrationRevealResponse,
    AvailableIntegration,
    AvailableIntegrationsResponse,
    UserIntegrationsResponse,
    IntegrationCreate,
    IntegrationUpdate,
    IntegrationValidateResponse,
)
from app.schemas.template import (
    VideoStructureConfig,
    VisualStyleConfig,
    AudioConfig,
    ScriptPromptConfig,
    PlatformOptimizationConfig,
    TemplateConfigSchema,
    TemplateCreate,
    TemplateUpdate,
    TemplateResponse,
    TemplateListItem,
    TemplateListResponse,
    TemplateConfigResponse,
)
from app.schemas.video import (
    VideoGenerationRequest,
    SwapIntegrationRequest,
    StepStatus,
    VideoStatusResponse,
    VideoResponse,
    VideoListItem,
    VideoListResponse,
    VideoGenerationResponse,
)
from app.schemas.social_account import (
    SocialAccountResponse,
    SocialAccountListResponse,
    OAuthInitResponse,
    OAuthCallbackResponse,
    DisconnectRequest,
)
from app.schemas.post import (
    PostCreate,
    PostUpdate,
    PostResponse,
    PostListResponse,
    CalendarDayItem,
    CalendarResponse,
    PostCreateResponse,
    PublishNowRequest,
)
from app.schemas.analytics import (
    AnalyticsMetrics,
    AnalyticsResponse,
    OverviewResponse,
    PlatformMetrics,
    PlatformComparisonResponse,
    PostAnalyticsResponse,
    TimeSeriesDataPoint,
    TimeSeriesResponse,
    TopPerformingItem,
    TopPerformingResponse,
    HeatmapResponse,
    SyncResponse,
    AnalyticsSyncRequest,
)
from app.schemas.suggestion import (
    SuggestionResponse,
    SuggestionListItem,
    SuggestionListResponse,
    UnreadCountResponse,
    PostingTimeAnalysis,
    PostingTimeResponse,
    ContentIdea,
    ContentIdeasResponse,
    TrendItem,
    TrendsResponse,
    PerformancePrediction,
    PerformancePredictionResponse,
    ImprovementItem,
    ImprovementsResponse,
    GenerateSuggestionsResponse,
    MarkReadRequest,
    DismissRequest,
    GenerateSuggestionsRequest,
)
from app.schemas.ai_suggestion_data import (
    AISuggestionData,
    SmartSuggestionResponse,
    ScheduleItem,
    VideoSeriesPlan,
    MonthlyContentPlan,
    SingleVideoActionData,
    SeriesActionData,
    MonthlyPlanActionData,
    ScheduleActionData,
)
from app.schemas.ai_chat import (
    ActionCard,
    ChatMessage,
    ChatMessageRequest,
    ExecuteActionRequest,
    ChatMessageResponse,
    ChatSessionResponse,
    ChatSessionListItem,
    ChatSessionListResponse,
    ExecuteActionResponse,
)
from app.schemas.video_planning import (
    ScheduleVideoRequest,
    CreateSeriesRequest,
    CreateMonthlyPlanRequest,
    UpdatePlannedVideoRequest,
    PlannedVideoResponse,
    ScheduleVideoResponse,
    CreateSeriesResponse,
    CreateMonthlyPlanResponse,
    PlannedVideoListResponse,
    TriggerGenerationResponse,
    CalendarVideoItem,
    CalendarViewResponse,
)
from app.schemas.notification import (
    NotificationResponse,
    NotificationListItem,
    NotificationListResponse,
    UnreadCountResponse as NotificationUnreadCountResponse,
    MarkReadResponse,
    DismissResponse,
    MarkReadRequest as NotificationMarkReadRequest,
    DismissRequest as NotificationDismissRequest,
    BroadcastRequest,
    BroadcastResponse,
)
from app.schemas.admin import (
    AdminUserItem,
    AdminUserListResponse,
    AdminUserStats,
    AdminUserDetailResponse,
    UpdateUserRoleRequest,
    UpdateUserStatusRequest,
    UserStats,
    VideoStats,
    PostStats,
    SubscriptionStats,
    PlatformStatsResponse,
    DailyDataPoint,
    ActivityStatsResponse,
    TopUserItem,
    TopUsersResponse,
    SettingItem,
    SettingsResponse,
    SetSettingRequest,
    FeatureFlags,
    SystemLimits,
    TemplateUsageItem,
    TemplateStatsResponse,
)
from app.schemas.user_generation_settings import (
    ProviderInfo,
    CategoryProviders,
    SubtitleStyleInfo,
    UserGenerationSettingsResponse,
    UserGenerationSettingsUpdate,
    CostBreakdownItem,
    CostEstimateResponse,
    AvailableProvidersResponse,
    EffectiveProvidersResponse,
)
from app.schemas.video_actions import (
    GenerateNowRequest,
    GenerateNowResponse,
    CancelVideoRequest,
    CancelVideoResponse,
    RetryVideoRequest,
    RetryVideoResponse,
    RescheduleVideoRequest,
    RescheduleVideoResponse,
    EditVideoRequest,
    EditVideoResponse,
    ScheduledVideoResponse,
    ScheduledVideosListResponse,
    VideoGenerationStatus,
)
from app.schemas.api_logs import (
    APILogResponse,
    APILogDetailResponse,
    APILogsListResponse,
    APILogsSearchParams,
    ProviderStatsResponse,
    AllProviderStatsResponse,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampSchema",
    "IDSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",
    "MessageResponse",
    
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "RoleUpdate",
    "StatusUpdate",
    "UserResponse",
    "UserProfileResponse",
    "UserListResponse",
    "UserStatsResponse",
    "FirebaseTokenRequest",
    "LoginResponse",
    "SetupStatusResponse",
    
    # Subscription
    "SubscriptionResponse",
    "SubscriptionStatusResponse",
    "PlanFeatures",
    "PlanInfo",
    "PlansResponse",
    "CheckoutRequest",
    "CheckoutResponse",
    "PortalResponse",
    "WebhookResponse",
    
    # Integration
    "IntegrationResponse",
    "IntegrationRevealResponse",
    "AvailableIntegration",
    "AvailableIntegrationsResponse",
    "UserIntegrationsResponse",
    "IntegrationCreate",
    "IntegrationUpdate",
    "IntegrationValidateResponse",
    
    # Template
    "VideoStructureConfig",
    "VisualStyleConfig",
    "AudioConfig",
    "ScriptPromptConfig",
    "PlatformOptimizationConfig",
    "TemplateConfigSchema",
    "TemplateCreate",
    "TemplateUpdate",
    "TemplateResponse",
    "TemplateListItem",
    "TemplateListResponse",
    "TemplateConfigResponse",
    
    # Video
    "VideoGenerationRequest",
    "SwapIntegrationRequest",
    "StepStatus",
    "VideoStatusResponse",
    "VideoResponse",
    "VideoListItem",
    "VideoListResponse",
    "VideoGenerationResponse",
    
    # Social Account
    "SocialAccountResponse",
    "SocialAccountListResponse",
    "OAuthInitResponse",
    "OAuthCallbackResponse",
    "DisconnectRequest",
    
    # Post
    "PostCreate",
    "PostUpdate",
    "PostResponse",
    "PostListResponse",
    "CalendarDayItem",
    "CalendarResponse",
    "PostCreateResponse",
    "PublishNowRequest",
    
    # Analytics
    "AnalyticsMetrics",
    "AnalyticsResponse",
    "OverviewResponse",
    "PlatformMetrics",
    "PlatformComparisonResponse",
    "PostAnalyticsResponse",
    "TimeSeriesDataPoint",
    "TimeSeriesResponse",
    "TopPerformingItem",
    "TopPerformingResponse",
    "HeatmapResponse",
    "SyncResponse",
    "AnalyticsSyncRequest",
    
    # Suggestion
    "SuggestionResponse",
    "SuggestionListItem",
    "SuggestionListResponse",
    "UnreadCountResponse",
    "PostingTimeAnalysis",
    "PostingTimeResponse",
    "ContentIdea",
    "ContentIdeasResponse",
    "TrendItem",
    "TrendsResponse",
    "PerformancePrediction",
    "PerformancePredictionResponse",
    "ImprovementItem",
    "ImprovementsResponse",
    "GenerateSuggestionsResponse",
    "MarkReadRequest",
    "DismissRequest",
    "GenerateSuggestionsRequest",
    
    # AI Suggestion Data
    "AISuggestionData",
    "SmartSuggestionResponse",
    "ScheduleItem",
    "VideoSeriesPlan",
    "MonthlyContentPlan",
    "SingleVideoActionData",
    "SeriesActionData",
    "MonthlyPlanActionData",
    "ScheduleActionData",
    
    # AI Chat
    "ActionCard",
    "ChatMessage",
    "ChatMessageRequest",
    "ExecuteActionRequest",
    "ChatMessageResponse",
    "ChatSessionResponse",
    "ChatSessionListItem",
    "ChatSessionListResponse",
    "ExecuteActionResponse",
    
    # Video Planning
    "ScheduleVideoRequest",
    "CreateSeriesRequest",
    "CreateMonthlyPlanRequest",
    "UpdatePlannedVideoRequest",
    "PlannedVideoResponse",
    "ScheduleVideoResponse",
    "CreateSeriesResponse",
    "CreateMonthlyPlanResponse",
    "PlannedVideoListResponse",
    "TriggerGenerationResponse",
    "CalendarVideoItem",
    "CalendarViewResponse",
    
    # Notification
    "NotificationResponse",
    "NotificationListItem",
    "NotificationListResponse",
    "NotificationUnreadCountResponse",
    "MarkReadResponse",
    "DismissResponse",
    "NotificationMarkReadRequest",
    "NotificationDismissRequest",
    "BroadcastRequest",
    "BroadcastResponse",
    
    # Admin
    "AdminUserItem",
    "AdminUserListResponse",
    "AdminUserStats",
    "AdminUserDetailResponse",
    "UpdateUserRoleRequest",
    "UpdateUserStatusRequest",
    "UserStats",
    "VideoStats",
    "PostStats",
    "SubscriptionStats",
    "PlatformStatsResponse",
    "DailyDataPoint",
    "ActivityStatsResponse",
    "TopUserItem",
    "TopUsersResponse",
    "SettingItem",
    "SettingsResponse",
    "SetSettingRequest",
    "FeatureFlags",
    "SystemLimits",
    "TemplateUsageItem",
    "TemplateStatsResponse",
    
    # User Generation Settings
    "ProviderInfo",
    "CategoryProviders",
    "SubtitleStyleInfo",
    "UserGenerationSettingsResponse",
    "UserGenerationSettingsUpdate",
    "CostBreakdownItem",
    "CostEstimateResponse",
    "AvailableProvidersResponse",
    "EffectiveProvidersResponse",
    
    # Video Actions
    "GenerateNowRequest",
    "GenerateNowResponse",
    "CancelVideoRequest",
    "CancelVideoResponse",
    "RetryVideoRequest",
    "RetryVideoResponse",
    "RescheduleVideoRequest",
    "RescheduleVideoResponse",
    "EditVideoRequest",
    "EditVideoResponse",
    "ScheduledVideoResponse",
    "ScheduledVideosListResponse",
    "VideoGenerationStatus",
    
    # API Logs
    "APILogResponse",
    "APILogDetailResponse",
    "APILogsListResponse",
    "APILogsSearchParams",
    "ProviderStatsResponse",
    "AllProviderStatsResponse",
]
